language: scala
sudo: false
matrix:
  include:
    - scala: 2.11.11
      jdk: oraclejdk8
      script: umask 0022 && ./sbt ++$TRAVIS_SCALA_VERSION clean coverage storehaus-kafka/test coverageReport mimaReportBinaryIssues
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - scala: 2.12.2 
      jdk: oraclejdk8
      script: umask 0022 && ./sbt ++$TRAVIS_SCALA_VERSION clean coverage storehaus-kafka/test coverageReport mimaReportBinaryIssues
      after_success:
        - bash <(curl -s https://codecov.io/bash)
before_script:
  - sleep 15 # https://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - mysql -u root -e "create database storehaus_test;"
  - mysql -u root -e "create user 'storehaususer'@'localhost' identified by 'test1234';"
  - mysql -u root -e "grant all on storehaus_test.* to 'storehaususer'@'localhost';"
services:
  - mysql
  - redis-server
  - memcache
  - mongodb
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4e859a6b499b2b68a647
    on_success: change
    on_failure: always
    on_start: never
