language: scala
sudo: false
scala:
  - 2.10.5
  - 2.11.7
before_script:
  - mysql -u root -e "create database storehaus_test;"
  - mysql -u root -e "create user 'storehaususer'@'localhost' identified by 'test1234';"
  - mysql -u root -e "grant all on storehaus_test.* to 'storehaususer'@'localhost';"
services:
  - redis-server
  - memcache
  - mongodb
script: umask 0022 && sbt ++$TRAVIS_SCALA_VERSION test
