language: scala
scala:
  - 2.10.3
  - 2.9.3
before_script:
  - mysql -u root -e "create database storehaus_test;"
  - mysql -u root -e "create user 'storehaususer'@'localhost' identified by 'test1234';"
  - mysql -u root -e "grant all on storehaus_test.* to 'storehaususer'@'localhost';"
services:
  - redis-server
  - memcache
script: umask 0022 && sbt ++$TRAVIS_SCALA_VERSION test
